const sampleListings = [
  {
    title: "Cozy Beachside Villa",
    description: "A peaceful villa with beautiful sea views and a relaxing atmosphere.",
    price: 4200,
    location: "Goa",
    country: "India",
    coordinates: [73.8567, 15.4909],
  },
  {
    title: "Mountain View Cottage",
    description: "A charming cottage surrounded by mountains and pine forests.",
    price: 3500,
    location: "Manali",
    country: "India",
    coordinates: [77.1892, 32.2396],
  },
  {
    title: "Lakeside Retreat",
    description: "A comfortable stay overlooking the beautiful Dal Lake.",
    price: 4800,
    location: "Srinagar",
    country: "India",
    coordinates: [74.7973, 34.0837],
  },
  {
    title: "Royal Heritage Haveli",
    description: "Experience traditional Rajasthani architecture in a beautiful haveli.",
    price: 5200,
    location: "Jaipur",
    country: "India",
    coordinates: [75.7873, 26.9124],
  },
  {
    title: "Desert Camp Stay",
    description: "Enjoy a unique desert experience with traditional food and music.",
    price: 3000,
    location: "Jaisalmer",
    country: "India",
    coordinates: [70.6794, 26.9157],
  },
  {
    title: "Forest Cabin",
    description: "A quiet wooden cabin surrounded by lush green forests.",
    price: 2800,
    location: "Wayanad",
    country: "India",
    coordinates: [76.1320, 11.6854],
  },
  {
    title: "Hilltop Escape",
    description: "A scenic hilltop property perfect for a peaceful vacation.",
    price: 3900,
    location: "Shimla",
    country: "India",
    coordinates: [77.1734, 31.1048],
  },
  {
    title: "Riverside Homestay",
    description: "A cozy homestay located beside the beautiful Ganges.",
    price: 2400,
    location: "Rishikesh",
    country: "India",
    coordinates: [78.2676, 30.0869],
  },
  {
    title: "Tea Garden Cottage",
    description: "Stay among beautiful tea gardens and enjoy the peaceful hills.",
    price: 3200,
    location: "Munnar",
    country: "India",
    coordinates: [77.0595, 10.0889],
  },
  {
    title: "Colonial Hill House",
    description: "A classic hill house with beautiful colonial architecture.",
    price: 4500,
    location: "Ooty",
    country: "India",
    coordinates: [76.6932, 11.4102],
  },

  {
    title: "Modern City Apartment",
    description: "A stylish apartment located close to major attractions.",
    price: 2600,
    location: "Mumbai",
    country: "India",
    coordinates: [72.8777, 19.0760],
  },
  {
    title: "Luxury Skyline Apartment",
    description: "Modern apartment offering stunning views of the city skyline.",
    price: 5000,
    location: "Bengaluru",
    country: "India",
    coordinates: [77.5946, 12.9716],
  },
  {
    title: "Peaceful Garden Home",
    description: "A spacious home with a beautiful private garden.",
    price: 2900,
    location: "Pune",
    country: "India",
    coordinates: [73.8567, 18.5204],
  },
  {
    title: "Old City Heritage Stay",
    description: "A traditional home located in the heart of the old city.",
    price: 2700,
    location: "Delhi",
    country: "India",
    coordinates: [77.1025, 28.7041],
  },
  {
    title: "Lake Palace View",
    description: "A luxurious stay offering beautiful views of Lake Pichola.",
    price: 6500,
    location: "Udaipur",
    country: "India",
    coordinates: [73.7125, 24.5854],
  },
  {
    title: "Fort View Residence",
    description: "Stay close to one of India's most famous historic forts.",
    price: 3600,
    location: "Jodhpur",
    country: "India",
    coordinates: [73.0243, 26.2389],
  },
  {
    title: "Backwater Houseboat",
    description: "A unique houseboat experience surrounded by Kerala backwaters.",
    price: 5500,
    location: "Alappuzha",
    country: "India",
    coordinates: [76.3388, 9.4981],
  },
  {
    title: "Tropical Beach House",
    description: "A bright beach house just minutes away from the ocean.",
    price: 4100,
    location: "Gokarna",
    country: "India",
    coordinates: [74.3141, 14.5502],
  },
  {
    title: "Portuguese Villa",
    description: "A beautiful heritage villa inspired by Portuguese architecture.",
    price: 4700,
    location: "Panaji",
    country: "India",
    coordinates: [73.8278, 15.4909],
  },
  {
    title: "Coastal Sunset Home",
    description: "Enjoy spectacular sunsets from this peaceful coastal property.",
    price: 3300,
    location: "Varkala",
    country: "India",
    coordinates: [76.7162, 8.7379],
  },

  {
    title: "Snow Valley Chalet",
    description: "A warm and comfortable chalet surrounded by snowy mountains.",
    price: 5800,
    location: "Gulmarg",
    country: "India",
    coordinates: [74.3805, 34.0484],
  },
  {
    title: "Apple Orchard Cottage",
    description: "A cozy cottage surrounded by beautiful apple orchards.",
    price: 3100,
    location: "Manali",
    country: "India",
    coordinates: [77.1892, 32.2396],
  },
  {
    title: "Himalayan Sunrise Lodge",
    description: "Wake up to spectacular views of the Himalayan mountains.",
    price: 4000,
    location: "Mussoorie",
    country: "India",
    coordinates: [78.0740, 30.4598],
  },
  {
    title: "Valley View Retreat",
    description: "A peaceful retreat overlooking the beautiful valley.",
    price: 3700,
    location: "Nainital",
    country: "India",
    coordinates: [79.4636, 29.3919],
  },
  {
    title: "Riverside Mountain Cabin",
    description: "A wooden cabin located beside a peaceful mountain river.",
    price: 3400,
    location: "Kasol",
    country: "India",
    coordinates: [77.3150, 32.0095],
  },
  {
    title: "Tea Estate Villa",
    description: "Relax in a beautiful villa surrounded by tea plantations.",
    price: 4300,
    location: "Darjeeling",
    country: "India",
    coordinates: [88.2636, 27.0410],
  },
  {
    title: "Hillside Wooden Home",
    description: "A peaceful wooden home with panoramic mountain views.",
    price: 3600,
    location: "Gangtok",
    country: "India",
    coordinates: [88.6138, 27.3389],
  },
  {
    title: "Cloud Valley Cottage",
    description: "A quiet cottage surrounded by clouds and green hills.",
    price: 2900,
    location: "Shillong",
    country: "India",
    coordinates: [91.8933, 25.5788],
  },
  {
    title: "Waterfall View Cottage",
    description: "A relaxing cottage located close to beautiful waterfalls.",
    price: 2700,
    location: "Cherrapunji",
    country: "India",
    coordinates: [91.6962, 25.2702],
  },
  {
    title: "Mountain Forest Lodge",
    description: "A secluded lodge surrounded by dense mountain forests.",
    price: 3800,
    location: "Tawang",
    country: "India",
    coordinates: [94.9120, 27.5860],
  },

  {
    title: "Royal Palace Stay",
    description: "A luxurious heritage property inspired by royal architecture.",
    price: 7200,
    location: "Mysore",
    country: "India",
    coordinates: [76.6394, 12.2958],
  },
  {
    title: "Temple City Homestay",
    description: "A comfortable homestay close to famous temples and markets.",
    price: 2200,
    location: "Madurai",
    country: "India",
    coordinates: [78.1198, 9.9252],
  },
  {
    title: "French Quarter Home",
    description: "A charming home located in the colorful French Quarter.",
    price: 3400,
    location: "Puducherry",
    country: "India",
    coordinates: [79.8083, 11.9416],
  },
  {
    title: "Beachfront Retreat",
    description: "Wake up to the sound of waves at this beachfront property.",
    price: 4500,
    location: "Chennai",
    country: "India",
    coordinates: [80.2707, 13.0827],
  },
  {
    title: "Coffee Plantation Stay",
    description: "A peaceful stay surrounded by coffee plantations.",
    price: 3900,
    location: "Coorg",
    country: "India",
    coordinates: [75.8069, 12.3375],
  },
  {
    title: "Jungle Resort Cottage",
    description: "A relaxing jungle stay surrounded by nature and wildlife.",
    price: 4600,
    location: "Kabini",
    country: "India",
    coordinates: [76.3000, 11.9500],
  },
  {
    title: "Heritage Riverside Villa",
    description: "A traditional villa overlooking a peaceful river.",
    price: 4200,
    location: "Hampi",
    country: "India",
    coordinates: [76.4600, 15.3350],
  },
  {
    title: "Sunset Cliff House",
    description: "A beautiful home overlooking the sea from a dramatic cliff.",
    price: 4800,
    location: "Varkala",
    country: "India",
    coordinates: [76.7162, 8.7379],
  },
  {
    title: "Island Beach Cottage",
    description: "A peaceful island cottage surrounded by crystal-clear waters.",
    price: 6200,
    location: "Port Blair",
    country: "India",
    coordinates: [92.7265, 11.6234],
  },
  {
    title: "Coral Beach Villa",
    description: "A tropical villa perfect for a relaxing island vacation.",
    price: 6800,
    location: "Havelock Island",
    country: "India",
    coordinates: [92.9856, 12.0117],
  },

  {
    title: "City Palace Apartment",
    description: "A modern apartment located near the city's major attractions.",
    price: 3000,
    location: "Ahmedabad",
    country: "India",
    coordinates: [72.5714, 23.0225],
  },
  {
    title: "Riverside Ahmedabad Home",
    description: "A comfortable home located near the Sabarmati Riverfront.",
    price: 2500,
    location: "Ahmedabad",
    country: "India",
    coordinates: [72.5714, 23.0225],
  },
  {
    title: "Diamond City Apartment",
    description: "A modern apartment in a convenient part of Surat.",
    price: 2300,
    location: "Surat",
    country: "India",
    coordinates: [72.8311, 21.1702],
  },
  {
    title: "Beachside Diu Cottage",
    description: "A relaxing cottage close to the beaches of Diu.",
    price: 2800,
    location: "Diu",
    country: "India",
    coordinates: [70.9874, 20.7144],
  },
  {
    title: "Rann Desert Retreat",
    description: "Experience the unique landscape and culture of the Rann of Kutch.",
    price: 3500,
    location: "Kutch",
    country: "India",
    coordinates: [69.8478, 23.7337],
  },
  {
    title: "Gir Forest Lodge",
    description: "A comfortable lodge near the famous Gir forest.",
    price: 4000,
    location: "Sasan Gir",
    country: "India",
    coordinates: [70.7887, 21.1243],
  },
  {
    title: "Palitana Heritage Home",
    description: "A peaceful heritage home near the famous Jain temples.",
    price: 2600,
    location: "Palitana",
    country: "India",
    coordinates: [71.8314, 21.5254],
  },
  {
    title: "Vadodara Garden Villa",
    description: "A spacious villa with a beautiful garden and quiet surroundings.",
    price: 3200,
    location: "Vadodara",
    country: "India",
    coordinates: [73.1812, 22.3072],
  },
  {
    title: "Ankleshwar Comfort Stay",
    description: "A comfortable modern stay with easy access to local attractions.",
    price: 2100,
    location: "Ankleshwar",
    country: "India",
    coordinates: [73.0020, 21.6264],
  },
  {
    title: "Statue of Unity Retreat",
    description: "A peaceful property near the Statue of Unity and surrounding attractions.",
    price: 3800,
    location: "Kevadia",
    country: "India",
    coordinates: [73.7191, 21.8380],
  },
];

module.exports = { sampleListings };